# Generated by Django 4.1.7 on 2025-05-29 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pharmaceutical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name of the pharmaceutical.",
                        max_length=200,
                        verbose_name="Pharmaceutical Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Enter a description of the pharmaceutical.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates if this pharmaceutical is currently active.",
                        verbose_name="Is Active?",
                    ),
                ),
                (
                    "prescription_required",
                    models.BooleanField(
                        default=True,
                        help_text="Designates if this pharmaceutical requires a prescription.",
                        verbose_name="Prescription Required?",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Select the user that the pharmaceutical belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pharmaceutical",
                "verbose_name_plural": "Pharmaceuticals",
            },
        ),
    ]
