# Generated by Django 4.1.7 on 2025-05-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PiDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("operating_system", models.CharField(max_length=100)),
                ("host_name", models.CharField(max_length=100, unique=True)),
                (
                    "mac_address",
                    models.CharField(
                        blank=True,
                        help_text="Format: XX:XX:XX:XX:XX:XX",
                        max_length=17,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "ram",
                    models.CharField(
                        help_text="e.g., 500MB, .5GB, 2GB, 4GB, 8GB", max_length=50
                    ),
                ),
                (
                    "form_factor",
                    models.CharField(
                        choices=[
                            ("Pi4", "Raspberry Pi 4"),
                            ("Pi5", "Raspberry Pi 5"),
                            ("PiZero", "Raspberry Pi Zero"),
                            ("PiPico", "Raspberry Pi Pico"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pi Device",
                "verbose_name_plural": "Pi Devices",
                "ordering": ("name",),
            },
        ),
    ]
