# Generated by Django 4.1.7 on 2025-05-29 01:07

import base.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BehavioralInterviewQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="The text of the behavioral interview question.",
                        verbose_name="Text",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who created the behavioral interview question.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Behavioral Interview Questions",
            },
        ),
        migrations.CreateModel(
            name="BulletPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="The text of the bullet point.", verbose_name="Text"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who created the bullet point.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bullet Points",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the skill.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who created the skill.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Skills",
            },
            bases=(base.mixins.OrderableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="QuestionResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        help_text="The summary of the question response.",
                        max_length=500,
                        verbose_name="Summary",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="The text of the question response.",
                        verbose_name="Text",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="The behavioral interview question that the response is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="career_organizerator.behavioralinterviewquestion",
                        verbose_name="Behavioral Interview Question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who created the question response.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Question Responses",
            },
        ),
        migrations.CreateModel(
            name="Purpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="The text of the purpose.",
                        max_length=500,
                        verbose_name="Text",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who created the purpose.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Purposes",
            },
        ),
        migrations.CreateModel(
            name="ElevatorSpeech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        help_text="The theme of the elevator speech.",
                        max_length=255,
                        verbose_name="Theme",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="The text of the elevator speech.",
                        verbose_name="Text",
                    ),
                ),
                (
                    "bullet_points",
                    models.ManyToManyField(
                        help_text="The bullet points that can be used in the elevator speech.",
                        to="career_organizerator.bulletpoint",
                        verbose_name="Bullet Points",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who created the elevator speech.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Elevator Speeches",
            },
        ),
    ]
