# Generated by Django 4.1.7 on 2025-05-31 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of this tag.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The author of this tag.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note Tag",
                "verbose_name_plural": "Note Tags",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="UnimportantNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of this note.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="The content of this note.",
                        verbose_name="Content",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="A reference URL for this note.",
                        verbose_name="URL",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        help_text="Add an image for the note.",
                        null=True,
                        upload_to="unimportant_notes/",
                        verbose_name="Main Image",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tag",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tags for this note.",
                        related_name="unimportant_notes",
                        to="unimportant_notes.notetag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unimportant Note",
                "verbose_name_plural": "Unimportant Notes",
                "ordering": ("-created",),
            },
        ),
    ]
