activities = [
    "Make a scrapbook",
    "Sew pillow cases",
    "Clip coupons",
    "Remember famous people",
    "Read aloud from labels",
    "Identify states and capitols",
    "Count tickets",
    "Wipe off the patio furniture",
    "Sing favorite hymns",
    "Read out loud",
    "Use the vacuum cleaner",
    "Read classic short stories",
    "Play horse shoes",
    "Dye Easter eggs",
    "Bake cookies",
    "Have afternoon tea",
    "Make a fresh fruit salad",
    "Button clothes",
    "Prep food (ex. snap beans, mash potatoes, or peel apples)",
    "Water house plants",
    "Use a spray bottle with water on plants",
    "Have a spelling bee",
    "Look at family photographs",
    "Mold with Play Doh",
    "Sand wood",
    "Plant seeds indoors or out",
    "Color pictures",
    "Name the presidents",
    "Finish nursery rhymes",
    "Cook hot dogs outside",
    "Wipe off the table",
    "Make homemade ice cream",
    "Ask simple questions",
    "Make a family tree poster",
    "Make cream cheese mints",
    "Dance",
    "Fold clothes or sort socks",
    "Sweep the patio",
    "Have a calm pet in to visit",
    "Color a picture of our flag",
    "Look at a picture book",
    "Reminisce about the first kiss",
    "Wash silverware",
    "Fold towels",
    "Feed the ducks",
    "Read a letter out loud",
    "Make a Valentine collage",
    "Take a walk",
    "Give a manicure",
    "Cut out paper dolls",
    "Take a ride",
    "Remember great inventions",
    "Pop popcorn",
    "Put a simple puzzle together",
    "Make a collage from magazines",
    "Put together nuts and bolts",
    "Put coins into a jar",
    "Rake leaves",
    "Roll yarn into a ball",
    "Weed the flower bed",
    "Look out the window. 'What do you see?'",
    "Listen to music",
    "Make Christmas cards",
    "Play Pictionary",
    "Arrange fresh flowers",
    "Finish Bible quotes",
    "Take care of a fish tank",
    "Sort poker chips",
    "Sing Christmas carols",
    "Paint a sheet",
    "Decorate paper place mats",
    "Make homemade lemonade",
    "Finish famous sayings",
    "Fold clothes",
    "Clean out a pumpkin",
    "Put the silverware away",
    "Exercise",
    "Toss a ball",
    "Sort playing cards by their color",
    "Color paper shamrocks green",
    "Cut pictures out of greeting cards",
    "Rub in pleasant-scented hand lotions",
    "Read the daily newspaper out loud",
    "Look up names in a phone book",
    "Dress in red on a football Saturday",
    "Play favorite songs and sing together",
    "Put bird feed out for the birds",
    "Force bulbs for winter blooming",
    "Cut out pictures from magazines",
    "Make peanut butter sandwiches",
    "Make homemade applesauce",
    "Write a letter to a family member",
    "Reminisce about a favorite summer",
    "Cut up used paper for scratch paper",
    "Reminisce about the first day of school",
    "Read Reader's Digest out loud",
    "Look at pictures in National Geographic",
    "String Cheerios to hang outside for the birds",
    "Straighten underwear drawers",
    "Trace leaves and cut them out",
    "Sort objects such as beads by shape or color",
    "Say 'Tell me more' when they start talking about a memory",
    "Ask a friend, neighbor, or church acquaintance with a baby to visit",
]
