# Generated by Django 4.1.7 on 2025-05-31 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Temperature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "measurement",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="The temperature measurement in degrees Fahrenheit.",
                        max_digits=4,
                        verbose_name="Temperature Measurement",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject that gets their temperature measured.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temperatures",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Temperature Measurement",
                "verbose_name_plural": "Temperature Measurements",
            },
        ),
        migrations.CreateModel(
            name="Pulse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "bpm",
                    models.PositiveSmallIntegerField(
                        help_text="The pulse rate in beats per minute.",
                        verbose_name="Beats Per Minute",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user that measures their pulse.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pulses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pulse Measurement",
                "verbose_name_plural": "Pulse Measurements",
            },
        ),
        migrations.CreateModel(
            name="BodyWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "measurement",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The body weight measurement in pounds.",
                        max_digits=5,
                        verbose_name="Body Weight Measurement",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject that gets their body weight measured.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_weights",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Body Weight Measurement",
                "verbose_name_plural": "Body Weight Measurements",
            },
        ),
        migrations.CreateModel(
            name="BloodPressure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "systolic",
                    models.PositiveSmallIntegerField(
                        help_text="The systolic blood pressure reading.",
                        verbose_name="Systolic Blood Pressure",
                    ),
                ),
                (
                    "diastolic",
                    models.PositiveSmallIntegerField(
                        help_text="The diastolic blood pressure reading.",
                        verbose_name="Diastolic Blood Pressure",
                    ),
                ),
                (
                    "pulse",
                    models.PositiveSmallIntegerField(
                        help_text="The pulse rate in beats per minute.",
                        verbose_name="Pulse",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user that measures their blood pressure.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blood_pressures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Blood Pressure Measurements",
            },
        ),
    ]
