# Generated by Django 4.1.7 on 2025-05-31 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CognitiveDistortion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the cognitive distortion.",
                        max_length=150,
                        verbose_name="Cognative Distortion",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="The description of the cognitive distortion.",
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cognative Distortion",
                "verbose_name_plural": "Cognative Distortions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Thought",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A summary of the thought.",
                        max_length=250,
                        verbose_name="Summary",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="The description of the thought.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "cognitive_distortion",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The cognitive distortion of the thought.",
                        related_name="thoughts",
                        to="cbt.cognitivedistortion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user that has the thought.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thoughts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Thought",
                "verbose_name_plural": "Thoughts",
                "ordering": ["name"],
            },
        ),
    ]
